defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- datamodule: single
- hardware: example
- graph: multi_scale
- model: gnn
- training: lora
- _self_


# set to true to switch on config validation
config_validation: True

training:
  lora_config:
    r: 8
    lora_alpha: 32
    target_modules: ['mlp.0', 'mlp.2', 'dummy_layer']
    modules_to_save: ['node_data_extractor.1']
